-- This file contains offensive terms for the sole purpose of content moderation.
-- These terms are not endorsed or encouraged.
_G.badwords = {
    "fuc",
    "bitc",
    "nig",
    "ggot",
    "fag",
    "expl",
    "hitl",
    "slu",
    "touches",
    "rape",
    "raping",
    "ped",
    "wtf",
    "lmao",
    "anal",
    "anus",
    "ballsack",
    "balls",
    "bastard",
    "biatch",
    "bloody",
    "blow",
    "boll",
    "boner",
    "boob",
    "bugger",
    "bum",
    "butt",
    "clitoris",
    "cock",
    "coon",
    "crap",
    "cunt",
    "dick",
    "dildo",
    "dyke",
    "feck",
    "fellate",
    "fellatio",
    "felching",
    "f u c k",
    "fudge",
    "goddamn",
    "god damn",
    "homo",
    "gay",
    "jerk",
    "jizz",
    "cum",
    "knob",
    "penis",
    "dick",
    "piss",
    "prick",
    "pube",
    "pussy",
    "queer",
    "scrotum",
    "sex",
    "shit",
    "s hit",
    "sh1t",
    "smegma",
    "sperm",
    "tits",
    "spunk",
    "tosser",
    "turd",
    "twat",
    "vagina",
    "wank",
    "whore",
    "kids",
    "porn",
    "http",
    "incel",
    "add me",
    "@",
    "instagram",
    "disco",
    "cord",
    "tiktok",
    "tik tok",
    "bit.ly",
    "suck",
    "nuts",
    "arous",
    "children",
    "freak",
    "hack",
    "hate",
    "kill yourself",
    "end yourself",
    "kys",
    "self harm",
    "selfharm",
    "suicide",
    "end my life",
    "personal info",
    "password",
    "username",
    "dox",
    "address",
    "zipcode",
    "zip code",
    "dmca",
    "give head",
    "ggers",
    "hiti"
} -- if any of these words are found, strict filtering will be forcefully enabled in the game server
